spring.application.name=socialService
#import from .env file
#spring.config.import=optional:file:.env[.properties]

server.port=8081

target_grpc=localhost:9090

spring.flyway.enabled=true

logging.level.org.flywaydb=DEBUG

#DB config
spring.datasource.url=jdbc:postgresql://localhost:5434/social_service
spring.datasource.username=postgres
spring.datasource.password=postgres



#hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
